/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ProxyAdmin } from "./ProxyAdmin";
export type { StandardImpl } from "./StandardImpl";
export type { StandardImpl2 } from "./StandardImpl2";
